### ISSUE TITLE
Deleting closing bracket of last block freezes app

### ISSUE THREAD

**Issue by KyleleeSea** [KyleleeSea/codemirror-experiments#2]
Bug: When you delete the ending bracket of the last block, the editor freezes

To replicate: 
Use either your last style.grammar file or my style.grammar file, both cause this
Write canvas {
width = 400
}
Then try to delete the last bracket

This exists when I tested it in penrose editor integrated version
Tried turning off the autocomplete hook and this still happens

https://github.com/KyleleeSea/codemirror-experiments/assets/85892844/079a9ca4-d228-40e0-a567-3f88e2428275

<img width="1486" alt="Screenshot 2024-06-17 at 4 29 22 PM" src="https://github.com/KyleleeSea/codemirror-experiments/assets/85892844/cbabb8df-5583-4050-84ef-42f4647739ad">

ERROR
Invalid array length
RangeError: Invalid array length
    at Array.push (<anonymous>)
    at Stack.storeNode (http://localhost:3000/static/js/bundle.js:71940:19)
    at Stack.reduce (http://localhost:3000/static/js/bundle.js:71906:12)
    at Parse.advanceStack (http://localhost:3000/static/js/bundle.js:73087:13)
    at Parse.advanceFully (http://localhost:3000/static/js/bundle.js:73114:17)
    at Parse.runRecovery (http://localhost:3000/static/js/bundle.js:73141:25)
    at Parse.advance (http://localhost:3000/static/js/bundle.js:73018:100)
    at http://localhost:3000/static/js/bundle.js:49086:31
    at ParseContext.withContext (http://localhost:3000/static/js/bundle.js:49118:14)
    at ParseContext.work (http://localhost:3000/static/js/bundle.js:49077:17)

**Comment by KyleleeSea** [comment]
After a lot of experimentation the issue is with insert semi, working on this now

**Comment by KyleleeSea** [comment]
The specific line that breaks it is: Block { "{" sepBy<Statement, semi> "}" } in style.grammar
Putting print statements in styleTokens.js shows an infinite loop

https://github.com/KyleleeSea/codemirror-experiments/assets/85892844/d80f9144-f43f-4bc4-b4c3-f5e413b05c8c
